import streamlit as st
import pandas as pd
import numpy as np
import pickle

# -----------------------------------------------------------------------------
# 1. PAGE CONFIGURATION & STYLING
# -----------------------------------------------------------------------------
st.set_page_config(
    page_title="CKD Diagnostic Workspace",
    page_icon="🩺",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Premium Custom CSS
st.markdown("""
    <style>
    /* Main container styling */
    .main {
        background-color: #f8f9fa;
    }
    /* Metric Cards */
    .metric-card {
        background-color: #ffffff;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 4px 6px rgba(0,0,0,0.05);
        margin-bottom: 20px;
        border-left: 5px solid #3498db;
    }
    .metric-card.positive {
        border-left-color: #e74c3c;
    }
    .metric-card.negative {
        border-left-color: #2ecc71;
    }
    /* Headers */
    h1, h2, h3 {
        color: #2c3e50;
        font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
    }
    </style>
""", unsafe_allow_html=True)

# -----------------------------------------------------------------------------
# 2. CACHED MODEL & ARTIFACT LOADERS
# -----------------------------------------------------------------------------
@st.cache_resource
def load_ml_artifacts():
    """Loads the model, scale factor, and selected feature lists."""
    try:
        # Load the RFE Optimized Model
        with open('best_ckd_model_rfe.pkl', 'rb') as f:
            model = pickle.load(f)
        
        # Load Scaler (Handles both 'scaler.pkl' or your local copy 'scaler (2).pkl')
        try:
            with open('scaler.pkl', 'rb') as f:
                scaler = pickle.load(f)
        except FileNotFoundError:
            with open('scaler (2).pkl', 'rb') as f:
                scaler = pickle.load(f)

        # Load Selected Feature Names
        with open('feature_names_rfe.pkl', 'rb') as f:
            features = pickle.load(f)
            
        return model, scaler, features
    except Exception as e:
        st.error(f"Error loading artifact dependencies: {e}")
        return None, None, None

model, scaler, selected_features = load_ml_artifacts()

# Hardcoded fallback categorical mappings from the Colab LabelEncoder configuration
# (Ensures 'missing' text options map to exact integer mappings generated by fit_transform)
CATEGORICAL_MAPPINGS = {
    'sg':    {'1.005': 0, '1.010': 1, '1.015': 2, '1.020': 3, '1.025': 4, 'missing': 5},
    'rbc':   {'abnormal': 0, 'missing': 1, 'normal': 2},
    'pc':    {'abnormal': 0, 'missing': 1, 'normal': 2},
    'pcc':   {'missing': 0, 'notpresent': 1, 'present': 2},
    'ba':    {'missing': 0, 'notpresent': 1, 'present': 2},
    'htn':   {'missing': 0, 'no': 1, 'yes': 2},
    'dm':    {'missing': 0, 'no': 1, 'yes': 2},
    'cad':   {'missing': 0, 'no': 1, 'yes': 2},
    'appet': {'good': 0, 'missing': 1, 'poor': 2},
    'pe':    {'missing': 0, 'no': 1, 'yes': 2},
    'ane':   {'missing': 0, 'no': 1, 'yes': 2}
}

# Documentation definitions for features used to populate the UI dynamic components
FEATURE_DETAILS = {
    'age':   {'label': 'Age (years)', 'type': 'num', 'min': 1, 'max': 120, 'default': 50},
    'bp':    {'label': 'Blood Pressure (mm/Hg)', 'type': 'num', 'min': 50, 'max': 180, 'default': 80},
    'sg':    {'label': 'Specific Gravity', 'type': 'cat', 'options': ['1.005', '1.010', '1.015', '1.020', '1.025', 'missing']},
    'al':    {'label': 'Albumin (0 to 5)', 'type': 'num', 'min': 0, 'max': 5, 'default': 0},
    'su':    {'label': 'Sugar (0 to 5)', 'type': 'num', 'min': 0, 'max': 5, 'default': 0},
    'rbc':   {'label': 'Red Blood Cells', 'type': 'cat', 'options': ['normal', 'abnormal', 'missing']},
    'pc':    {'label': 'Pus Cell', 'type': 'cat', 'options': ['normal', 'abnormal', 'missing']},
    'pcc':   {'label': 'Pus Cell Clumps', 'type': 'cat', 'options': ['notpresent', 'present', 'missing']},
    'ba':    {'label': 'Bacteria', 'type': 'cat', 'options': ['notpresent', 'present', 'missing']},
    'bgr':   {'label': 'Blood Glucose Random (mg/dL)', 'type': 'num', 'min': 50, 'max': 500, 'default': 120},
    'bu':    {'label': 'Blood Urea (mg/dL)', 'type': 'num', 'min': 10, 'max': 400, 'default': 40},
    'sc':    {'label': 'Serum Creatinine (mg/dL)', 'type': 'num', 'min': 0.1, 'max': 15.0, 'default': 1.2},
    'sod':   {'label': 'Sodium (mEq/L)', 'type': 'num', 'min': 100, 'max': 180, 'default': 138},
    'pot':   {'label': 'Potassium (mEq/L)', 'type': 'num', 'min': 2.0, 'max': 10.0, 'default': 4.1},
    'hemo':  {'label': 'Hemoglobin (g/dL)', 'type': 'num', 'min': 3.0, 'max': 20.0, 'default': 13.5},
    'pcv':   {'label': 'Packed Cell Volume (%)', 'type': 'num', 'min': 10, 'max': 60, 'default': 40},
    'wbcc':  {'label': 'White Blood Cell Count (cells/cmm)', 'type': 'num', 'min': 2000, 'max': 30000, 'default': 8000},
    'rbcc':  {'label': 'Red Blood Cell Count (millions/cmm)', 'type': 'num', 'min': 2.0, 'max': 10.0, 'default': 4.8},
    'htn':   {'label': 'Hypertension', 'type': 'cat', 'options': ['no', 'yes', 'missing']},
    'dm':    {'label': 'Diabetes Mellitus', 'type': 'cat', 'options': ['no', 'yes', 'missing']},
    'cad':   {'label': 'Coronary Artery Disease', 'type': 'cat', 'options': ['no', 'yes', 'missing']},
    'appet': {'label': 'Appetite Status', 'type': 'cat', 'options': ['good', 'poor', 'missing']},
    'pe':    {'label': 'Pedal Edema', 'type': 'cat', 'options': ['no', 'yes', 'missing']},
    'ane':   {'label': 'Anemia', 'type': 'cat', 'options': ['no', 'yes', 'missing']}
}

# -----------------------------------------------------------------------------
# 3. INTERFACE HEADER & APP ENTRY POINT
# -----------------------------------------------------------------------------
st.markdown("# 🩺 Chronic Kidney Disease Predictive Intelligence Workspace")
st.markdown("Enter client clinical test measurements below to trigger prediction scoring via the RFE Optimized Ensemble Model.")
st.write("---")

if model is None or scaler is None or selected_features is None:
    st.error("Application setup broken. Ensure standard `.pkl` dependencies reside in runtime root directory.")
else:
    # Segment layout visually by test groups
    col1, col2 = st.columns(2)
    
    raw_user_inputs = {}
    
    # Dynamically separate features between Column 1 and Column 2
    for idx, feat_id in enumerate(selected_features):
        target_col = col1 if (idx % 2 == 0) else col2
        meta = FEATURE_DETAILS[feat_id]
        
        with target_col:
            if meta['type'] == 'num':
                # Preserve floating point variations based on typical values
                step_val = 0.1 if isinstance(meta['default'], float) else 1
                raw_user_inputs[feat_id] = st.number_input(
                    label=meta['label'],
                    min_value=float(meta['min']),
                    max_value=float(meta['max']),
                    value=float(meta['default']),
                    step=float(step_val),
                    key=f"input_{feat_id}"
                )
            elif meta['type'] == 'cat':
                raw_user_inputs[feat_id] = st.selectbox(
                    label=meta['label'],
                    options=meta['options'],
                    index=0,
                    key=f"input_{feat_id}"
                )

    st.write("---")
    
    # -----------------------------------------------------------------------------
    # 4. PREDICTION ENGINE PIPELINE
    # -----------------------------------------------------------------------------
    if st.button("Execute Predictive Diagnosis", type="primary", use_container_width=True):
        
        # Step A: Convert inputs into raw data list ordered exactly by the full 24 feature array
        full_features_list = [
            'age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr', 'bu', 
            'sc', 'sod', 'pot', 'hemo', 'pcv', 'wbcc', 'rbcc', 'htn', 'dm', 'cad', 
            'appet', 'pe', 'ane'
        ]
        
        processed_row = []
        for feat in full_features_list:
            # Fallback for missing input data if it isn't used by RFE
            current_val = raw_user_inputs.get(feat, FEATURE_DETAILS[feat].get('default', 'missing'))
            
            # Map Categorical selections using encoded mappings
            if FEATURE_DETAILS[feat]['type'] == 'cat':
                val_str = str(current_val)
                mapping_dict = CATEGORICAL_MAPPINGS.get(feat, {})
                encoded_val = mapping_dict.get(val_str, mapping_dict.get('missing', 0))
                processed_row.append(encoded_val)
            else:
                processed_row.append(float(current_val))
                
        # Prepare matrix for transform scaler
        full_sample_matrix = np.array([processed_row])
        
        # Step B: Scale the complete sample
        scaled_sample_matrix = scaler.transform(full_sample_matrix)
        
        # Step C: Extract RFE Masked Columns
        # Generate bool index mask matching names
        rfe_mask = [f_name in selected_features for f_name in full_features_list]
        final_input_vector = scaled_sample_matrix[:, rfe_mask]
        
        # Step D: Infer results
        prediction_class = model.predict(final_input_vector)[0]
        prediction_probability = model.predict_proba(final_input_vector)[0][1]
        
        # -----------------------------------------------------------------------------
        # 5. UI RESULTS OUTPUT
        # -----------------------------------------------------------------------------
        st.subheader("Diagnostic Results Dashboard")
        
        if prediction_class == 1:
            st.markdown(f"""
                <div class="metric-card positive">
                    <h3>⚠️ Chronic Kidney Disease Detected</h3>
                    <p>The RFE Optimized Ensemble Engine calculates a high likelihood of structural anomalies.</p>
                    <h2 style="color: #e74c3c; margin-top: 5px;">Probability Index: {prediction_probability * 100:.2f}%</h2>
                </div>
            """, unsafe_allow_html=True)
        else:
            st.markdown(f"""
                <div class="metric-card negative">
                    <h3>✅ No Signs of Chronic Kidney Disease Detected</h3>
                    <p>Measurements align closely within base thresholds of non-chronic baseline metrics.</p>
                    <h2 style="color: #2ecc71; margin-top: 5px;">Probability Index: {(1 - prediction_probability) * 100:.2f}%</h2>
                </div>
            """, unsafe_allow_html=True)
            
        # Optional: Print raw input configurations vector for diagnostic debug monitoring
        with st.expander("Show Scaled Pipeline Debug Vectors"):
            st.write("Processed Sample (Original Scale Array Structure):", processed_row)
            st.write("Final Scaled RFE Feature Input array passed to model:", final_input_vector)
